INSERT INTO ASSOCIADOS(NOME, CARGO, SEXO, DATA_NASCIMENTO) VALUES('Fulano', 'Prefeito' , 'Masculino', 19880319);
INSERT INTO ASSOCIADOS(NOME, CARGO, SEXO, DATA_NASCIMENTO) VALUES('Ciclano', 'Governador' , 'Masculino', 19620219);
INSERT INTO ASSOCIADOS(NOME, CARGO, SEXO, DATA_NASCIMENTO) VALUES('Beltrano', 'Presidente' , 'Feminino', 20000612);

INSERT INTO PARTIDOS(NOME, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES('Brasil Crypto', 'PC' , 'Direita', 19210218);
INSERT INTO PARTIDOS(NOME, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES('Brasil', 'PB' , 'Centro', 19320512 );
INSERT INTO PARTIDOS(NOME, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES('Estado Soberano', 'PE' , 'Esquerda', 18791212);