INSERT INTO ASSOCIADOS(NOME, CARGO, SEXO) VALUES('Fulano', 'Prefeito' , 'Masculino' );
INSERT INTO ASSOCIADOS(NOME, CARGO, SEXO) VALUES('Ciclano', 'Governador' , 'Masculino' );
INSERT INTO ASSOCIADOS(NOME, CARGO, SEXO) VALUES('Beltrano', 'Presidente' , 'Feminino' );

INSERT INTO PARTIDOS(NOME, SIGLA, IDEOLOGIA) VALUES('Brasil Crypto', 'PC' , 'Direita' );
INSERT INTO PARTIDOS(NOME, SIGLA, IDEOLOGIA) VALUES('Brasil', 'PB' , 'Centro' );
INSERT INTO PARTIDOS(NOME, SIGLA, IDEOLOGIA) VALUES('Estado Soberano', 'PE' , 'Esquerda' );